R4:
  resources:
    - Account
    - ActivityDefinition
    - AdverseEvent
    - AllergyIntolerance
    - Appointment
    - AppointmentResponse
    - AuditEvent
    - Basic
    - Binary
    - BiologicallyDerivedProduct
    - BodyStructure
    - Bundle
    - CapabilityStatement
    - CarePlan
    - CareTeam
    - CatalogEntry
    - ChargeItem
    - ChargeItemDefinition
    - Claim
    - ClaimResponse
    - ClinicalImpression
    - CodeSystem
    - Communication
    - CommunicationRequest
    - CompartmentDefinition
    - Composition
    - ConceptMap
    - Condition
    - Consent
    - Contract
    - Coverage
    - CoverageEligibilityRequest
    - CoverageEligibilityResponse
    - DetectedIssue
    - Device
    - DeviceDefinition
    - DeviceMetric
    - DeviceRequest
    - DeviceUseStatement
    - DiagnosticReport
    - DocumentManifest
    - DocumentReference
    - EffectEvidenceSynthesis
    - Encounter
    - Endpoint
    - EnrollmentRequest
    - EnrollmentResponse
    - EpisodeOfCare
    - EventDefinition
    - Evidence
    - EvidenceVariable
    - ExampleScenario
    - ExplanationOfBenefit
    - FamilyMemberHistory
    - Flag
    - Goal
    - GraphDefinition
    - Group
    - GuidanceResponse
    - HealthcareService
    - ImagingStudy
    - Immunization
    - ImmunizationEvaluation
    - ImmunizationRecommendation
    - ImplementationGuide
    - InsurancePlan
    - Invoice
    - Library
    - Linkage
    - List
    - Location
    - Measure
    - MeasureReport
    - Media
    - Medication
    - MedicationAdministration
    - MedicationDispense
    - MedicationKnowledge
    - MedicationRequest
    - MedicationStatement
    - MedicinalProduct
    - MedicinalProductAuthorization
    - MedicinalProductContraindication
    - MedicinalProductIndication
    - MedicinalProductIngredient
    - MedicinalProductInteraction
    - MedicinalProductManufactured
    - MedicinalProductPackaged
    - MedicinalProductPharmaceutical
    - MedicinalProductUndesirableEffect
    - MessageDefinition
    - MessageHeader
    - MolecularSequence
    - NamingSystem
    - NutritionOrder
    - Observation
    - ObservationDefinition
    - OperationDefinition
    - OperationOutcome
    - Organization
    - OrganizationAffiliation
    - Parameters
    - Patient
    - PaymentNotice
    - PaymentReconciliation
    - Person
    - PlanDefinition
    - Practitioner
    - PractitionerRole
    - Procedure
    - Provenance
    - Questionnaire
    - QuestionnaireResponse
    - RelatedPerson
    - RequestGroup
    - ResearchDefinition
    - ResearchElementDefinition
    - ResearchStudy
    - ResearchSubject
    - RiskAssessment
    - RiskEvidenceSynthesis
    - Schedule
    - SearchParameter
    - ServiceRequest
    - Slot
    - Specimen
    - SpecimenDefinition
    - StructureDefinition
    - StructureMap
    - Subscription
    - Substance
    - SubstanceNucleicAcid
    - SubstancePolymer
    - SubstanceProtein
    - SubstanceReferenceInformation
    - SubstanceSourceMaterial
    - SubstanceSpecification
    - SupplyDelivery
    - SupplyRequest
    - Task
    - TerminologyCapabilities
    - TestReport
    - TestScript
    - ValueSet
    - VerificationResult
    - VisionPrescription
  # Custom clinical resource configs
  # Default for all other resources
  #{'resourceType': 'MedicationRequest', 'id': 'fe0946a1-661b-565a-9272-7c1569e94cb2', 'meta': {'versionId': '1', 'lastUpdated': '2022-05-24T17:16:23.842-04:00', 'source': '#dkhMMmvv1PtPdrV5', 'profile': ['http://fhir.mimic.mit.edu/StructureDefinition/mimic-medication-request']}, 'identifier': [{'type': {'coding': [{'system': 'http://fhir.mimic.mit.edu/CodeSystem/identifier-type', 'code': 'PHID', 'display': 'Pharmacy identifier'}]}, 'system': 'http://fhir.mimic.mit.edu/identifier/medication-request', 'value': '48357112'}], 'status': 'completed', 'intent': 'order', 'medicationReference': {'reference': 'Medication/0f0ac5ff-6c40-5def-af56-bf696aa30ee9'}, 'subject': {'reference': 'Patient/cd462e42-c070-5235-ae76-c37733a451be'}, 'encounter': {'reference': 'Encounter/c7122e1e-d950-5bcd-90b9-6a2fbb1352e4'}, 'authoredOn': '2189-06-09T16:45:19-04:00', 'dosageInstruction': [{'text': '20mEq Packet', 'route': {'coding': [{'system': 'http://fhir.mimic.mit.edu/CodeSystem/medication-route', 'code': 'PO'}]}, 'doseAndRate': [{'doseQuantity': {'value': 80, 'unit': 'mEq', 'system': 'http://fhir.mimic.mit.edu/CodeSystem/units', 'code': 'mEq'}}]}], 'dispenseRequest': {'validityPeriod': {'start': '2189-06-09T17:00:00-04:00', 'end': '2189-06-10T23:00:00-04:00'}}}
  MedicationRequest:
    code:
      - const(resourceType)
      - const(//)
      - vocab(identifier[0][system])
      - const(//)
      - col(identifier[0][value])
    time: col(authoredOn)
  MedicationAdministration:
    code:
      - const(resourceType)
      - const(//)
      - vocab(identifier[0][system])
      - const(//)
      - col(identifier[0][value])
    time: col(authoredOn)
  MedicationDispense:
    code:
      - const(resourceType)
      - const(//)
      - vocab(medicationCodeableConcept[coding][0][system])
      - const(//)
      - col(medicationCodeableConcept[coding][0][code])
    time: col(authoredOn)
  Specimen:
    code:
      - const(resourceType)
      - const(//)
      - vocab(identifier[0][system])
      - const(//)
      - col(identifier[0][value])
    time: col(collection[0].collectedDateTime)
  Encounter:
    code:
      - const(resourceType)
      - const(//)
      - vocab(type[0][coding][0][system])
      - const(//)
      - col(type[0][coding][0][code])
    time:
      - col(period[start])
  default:
    code:
      - const(resourceType)
      - const(//)
      - vocab(code[coding][0][system])
      - const(//)
      - col(code[coding][0][code])
    time:
      - col(effectiveDateTime)
      - col(issued)
      - col(authoredOn)
      - col(performedDateTime)
      - col(onsetDateTime)
    numeric_value: col(valueQuantity.value)
    text_value: col(valueString)
    subject_id: col(subject.reference)
  Patient:
    code:
      - const(MEDS_BIRTH)
    time: col(birthDate)
R5:
  resources:
    - Account
    - ActivityDefinition
    - AdverseEvent
    - AllergyIntolerance
    - Appointment
    - AppointmentResponse
    - AuditEvent
    - Basic
    - Binary
    - BiologicallyDerivedProduct
    - BodyStructure
    - Bundle
    - CapabilityStatement
    - CarePlan
    - CareTeam
    - CatalogEntry
    - ChargeItem
    - ChargeItemDefinition
    - Claim
    - ClaimResponse
    - ClinicalImpression
    - CodeSystem
    - Communication
    - CommunicationRequest
    - CompartmentDefinition
    - Composition
    - ConceptMap
    - Condition
    - Consent
    - Contract
    - Coverage
    - CoverageEligibilityRequest
    - CoverageEligibilityResponse
    - DetectedIssue
    - Device
    - DeviceDefinition
    - DeviceMetric
    - DeviceRequest
    - DeviceUsage
    - DiagnosticReport
    - DocumentManifest
    - DocumentReference
    - Encounter
    - Endpoint
    - EnrollmentRequest
    - EnrollmentResponse
    - EpisodeOfCare
    - EventDefinition
    - Evidence
    - EvidenceReport
    - EvidenceVariable
    - ExampleScenario
    - ExplanationOfBenefit
    - FamilyMemberHistory
    - Flag
    - FormularyItem
    - GenomicStudy
    - Goal
    - GraphDefinition
    - Group
    - GuidanceResponse
    - HealthcareService
    - ImagingSelection
    - ImagingStudy
    - Immunization
    - ImmunizationEvaluation
    - ImmunizationRecommendation
    - ImplementationGuide
    - Ingredient
    - InsurancePlan
    - InventoryItem
    - InventoryReport
    - Invoice
    - Library
    - Linkage
    - List
    - Location
    - ManufacturedItemDefinition
    - Measure
    - MeasureReport
    - Medication
    - MedicationAdministration
    - MedicationDispense
    - MedicationKnowledge
    - MedicationRequest
    - MedicationStatement
    - MedicinalProductDefinition
    - MessageDefinition
    - MessageHeader
    - MolecularSequence
    - NamingSystem
    - NutritionIntake
    - NutritionOrder
    - NutritionProduct
    - Observation
    - ObservationDefinition
    - OperationDefinition
    - OperationOutcome
    - Organization
    - OrganizationAffiliation
    - PackagedProductDefinition
    - Parameters
    - Patient
    - PaymentNotice
    - PaymentReconciliation
    - Person
    - PlanDefinition
    - Practitioner
    - PractitionerRole
    - Procedure
    - Provenance
    - Questionnaire
    - QuestionnaireResponse
    - RegulatedAuthorization
    - RelatedPerson
    - RequestOrchestration
    - Requirements
    - ResearchStudy
    - ResearchSubject
    - RiskAssessment
    - Schedule
    - SearchParameter
    - ServiceRequest
    - Slot
    - Specimen
    - SpecimenDefinition
    - StructureDefinition
    - StructureMap
    - Subscription
    - SubscriptionStatus
    - SubscriptionTopic
    - Substance
    - SubstanceDefinition
    - SupplyDelivery
    - SupplyRequest
    - Task
    - TerminologyCapabilities
    - TestPlan
    - TestReport
    - TestScript
    - Transport
    - ValueSet
    - VerificationResult
    - VisionPrescription
  # Custom clinical resource configs
  MedicationRequest:
    code:
      - const(resourceType)
      - const(//)
      - vocab(identifier[0][system])
      - const(//)
      - col(identifier[0][value])
    time: col(authoredOn)
  MedicationAdministration:
    code:
      - const(resourceType)
      - const(//)
      - vocab(identifier[0][system])
      - const(//)
      - col(identifier[0][value])
    time: col(authoredOn)
  MedicationDispense:
    code:
      - const(resourceType)
      - const(//)
      - vocab(medicationCodeableConcept[coding][0][system])
      - const(//)
      - col(medicationCodeableConcept[coding][0][code])
    time: col(authoredOn)
  Specimen:
    code:
      - const(resourceType)
      - const(//)
      - vocab(identifier[0][system])
      - const(//)
      - col(identifier[0][value])
    time: col(collection[0].collectedDateTime)
  Encounter:
    code:
      - const(resourceType)
      - const(//)
      - vocab(type[0][coding][0][system])
      - const(//)
      - col(type[0][coding][0][code])
    time:
      - col(period[start])
  default:
    code:
      - const(resourceType)
      - const(//)
      - vocab(code[coding][0][system])
      - const(//)
      - col(code[coding][0][code])
    time:
      - col(effectiveDateTime)
      - col(issued)
      - col(authoredOn)
      - col(performedDateTime)
      - col(onsetDateTime)
    numeric_value: col(valueQuantity.value)
    text_value: col(valueString)
    subject_id: col(subject.reference)
  Patient:
    code:
      - const(MEDS_BIRTH)
    time: col(birthDate)